. "C:\Program Files\WindowsPowerShell\Scripts\ApiTool.ps1"
. "C:\Program Files\WindowsPowerShell\Scripts\touch.ps1"
. "C:\Program Files\WindowsPowerShell\Scripts\Zip-Converter.ps1"
. "C:\Program Files\WindowsPowerShell\Scripts\Optimize-MP4.ps1"
Write-Host "Consider giving it a star if you like it: https://github.com/Anen135/powershellScripts"