. "C:\projects\powershell\powershellScripts\ApiTool.ps1"
. "C:\projects\powershell\powershellScripts\touch.ps1"
. "C:\projects\powershell\powershellScripts\Zip-Converter.ps1"
. "C:\projects\powershell\powershellScripts\Optimize-MP4.ps1"
Write-Host "Consider giving it a star if you like it: https://github.com/Anen135/powershellScripts"